export const AUTH_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    CHECK_AUTH: 'CHECK_AUTH',
    INSTALL_CATEGORY: 'INSTALL_CATEGORY',
    UPDATE_META: 'UPDATE_META',

  };